# yml 파일 포맷 version
version: "3"


# 컨테이너 목록
services:
  # Django container
  django:
    # 컨테이너 명
    container_name: akashic_django
    # docker build 옵션
    build:
      # docker build 명령어를 실행할 디렉토리 경로
      context: .
      # 지정할 Dockerfile 경로
      dockerfile: ./Dockerfile
    # 현재 디렉토리를 컨테이너 내 /home/에 마운트
    volumes:
      - ./:/home/
    # 작업 폴더 지정
    working_dir : /home/
    # 실행할 명령어
    command: >
      bash -c "
      python3 manage.py runserver 0.0.0.0:8000"
    # 호스트 OS와 컨테이너의 포트를 바인딩
    ports:
      - "8000:8000"
    # 호스트 OS에 포트를 공개하지 않고 컨테이너만 포트를 공개 (현재는 주석)
    #expose:
    #  - "8000"

